#!/bin/bash

AWS_ACCESS_KEY=
AWS_SECRET_KEY=
[ -z ${AWS_ACCESS_KEY} ] && echo "AWS_ACCESS_KEY MUST BE SET!" && exit 1
[ -z ${AWS_SECRET_KEY} ] && echo "AWS_SECRET_KEY MUST BE SET!" && exit 1
echo $AWS_ACCESS_KEY
# set defaults
[ -z ${IP_ADDRESS} ] && IP_ADDRESS=1.1.1.1

java -DawsAccessKey="${AWS_ACCESS_KEY}" \
    -DawsSecretKey="${AWS_SECRET_KEY}" \
    -DipAddress="${IP_ADDRESS}" \
    -cp ./target/automation-grid.jar org.openqa.grid.selenium.GridLauncher \
    -role hub \
    -servlets "com.rmn.qa.servlet.AutomationTestRunServlet","com.rmn.qa.servlet.StatusServlet" \
    -DPOOL_MAX=1024 \
    -DtotalNodeCount=325 \
    -hubConfig hub.static.json \
    -log grid.log \
    -DpropertyFileLocation=/Users/xxxxxx/tools/GridScale/aws.properties
